[build]
  command = "vite build"
[[redirects]]
  from = "/api*"
  to = "https://payment-application-backend.netlify.app/.netlify/functions/:splat"
  status = 200
  force = true
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"