[build]
  command = "vite build"

[[redirects]]
  from = "/api/v1/*"
  to = "https://payment-application-backend.netlify.app/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
