[build]
  functions = "netlify/functions/"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
  access-control-allow-origin = "*"