[build]
  functions = "netlify/functions/"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"